# Configuração do SonarQube para o projeto ms-video-slice
sonar.projectKey=11soat-hackton-videoslice_ms-video-slice
sonar.organization=11soat-hackton-videoslice
sonar.projectName=ms-video-slice
sonar.token=${SONAR_TOKEN}
sonar.projectVersion=1.0
sonar.branch.name=master
sonar.qualitygate.wait=true

# Diretórios de código fonte
sonar.sources=src
sonar.tests=tests

# Diretório de exclusões
sonar.exclusions=**/__pycache__/**,**/__init__.py,**/tests/**,**/exemplo_rapido_test.py

# Linguagem
sonar.language=py
sonar.python.version=3.14

# Cobertura de testes
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/**,**/__init__.py

# Encoding
sonar.sourceEncoding=UTF-8

# Métricas de qualidade
sonar.python.xunit.reportPath=test-results.xml
